In [1]:
import numpy as np

# Создание массива

In [2]:
a = [12, 29, 44]
np.array(a)

array([12, 29, 44])

In [3]:
a = [(1, 2), (3, 4)]
np.array(a)

array([[1, 2],
       [3, 4]])

In [4]:
a = [[1, 4], [50, 11]]
np.array(a, dtype=np.float32)

array([[ 1.,  4.],
       [50., 11.]], dtype=float32)

# Информация о массиве

In [5]:
a = np.arange(15, dtype=np.int32)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a = a.reshape((3, 5))

In [7]:
type(a)

numpy.ndarray

In [8]:
a.ndim

2

In [9]:
a.shape

(3, 5)

In [10]:
a.size

15

In [11]:
a.dtype

dtype('int32')

In [12]:
a.itemsize

4

# Заполнение данными по умолчанию

In [13]:
np.zeros((2, 4, 3), dtype=np.int8)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int8)

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.empty((3, 6))

array([[3.28700213e-288, 6.36541413e-288, 4.45469735e-308,
        1.64350420e-288, 2.66964936e-288, 1.84874200e-288],
       [3.08010147e-288, 3.08010771e-288, 2.15658852e-288,
        4.45471857e-308, 2.15656973e-288, 5.54448480e-288],
       [2.36015879e-288, 3.28700213e-288, 1.64351359e-288,
        2.87486211e-288, 2.15657756e-288, 2.30452256e-311]])

In [16]:
np.arange(10, 21, 2)

array([10, 12, 14, 16, 18, 20])

In [17]:
np.linspace(1, 2, 11)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [18]:
np.random.rand(2, 3)

array([[0.57938545, 0.10368207, 0.97491026],
       [0.16190703, 0.59116772, 0.51177173]])

In [19]:
np.random.randint(1, 10, (3, 2))

array([[9, 6],
       [4, 2],
       [5, 4]])

In [20]:
np.random.default_rng().choice(20, size=10, replace=False)

array([11,  7,  4,  9,  0, 18,  5, 14, 10,  6], dtype=int64)

In [21]:
a = np.arange(20)
np.random.shuffle(a)
a[:10]

array([19,  7, 13,  5,  3,  8,  9,  4,  1, 15])

# Базовые операции

In [22]:
a = np.random.randint(1, 10, 4)
b = np.arange(4)

a, b, a + b

(array([1, 7, 1, 3]), array([0, 1, 2, 3]), array([1, 8, 3, 6]))

In [23]:
a - b

array([ 1,  6, -1,  0])

In [24]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [25]:
np.sin(b)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [26]:
b, b < 2

(array([0, 1, 2, 3]), array([ True,  True, False, False]))

In [27]:
A = np.array([[3, 1],
              [0, 10]])

B = np.array([[2, 0],
              [3, 4]])

In [28]:
A*B

array([[ 6,  0],
       [ 0, 40]])

In [29]:
A @ B

array([[ 9,  4],
       [30, 40]])

In [30]:
A.dot(B)

array([[ 9,  4],
       [30, 40]])

In [31]:
A += 1
A

array([[ 4,  2],
       [ 1, 11]])

In [32]:
B *= 2

In [33]:
B

array([[4, 0],
       [6, 8]])

# Множественные операции

In [34]:
a = np.random.default_rng(1).random((2, 4))
a

array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945],
       [0.31183145, 0.42332645, 0.82770259, 0.40919914]])

In [35]:
a.sum()

4.527154012055734

In [36]:
a.min()

0.14415961271963373

In [37]:
a.max()

0.9504636963259353

In [38]:
a.sum(axis=0)

array([0.82365308, 1.37379015, 0.97186221, 1.35784858])

In [39]:
a.sum(axis=1)

array([2.55509438, 1.97205963])

In [40]:
a.cumsum(axis=1)

array([[0.51182162, 1.46228532, 1.60644493, 2.55509438],
       [0.31183145, 0.7351579 , 1.56286049, 1.97205963]])

# Индексация нарезка и итерация

## Одномерный массив (как со списками)

In [41]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [42]:
a[3]

9

In [43]:
a[1:3]

array([1, 4], dtype=int32)

In [44]:
a[:6:2]

array([ 0,  4, 16], dtype=int32)

In [45]:
a[:8:2] = 1000

In [46]:
a

array([1000,    1, 1000,    9, 1000,   25, 1000,   49,   64,   81],
      dtype=int32)

In [47]:
for i in a:
    print(i%10)

0
1
0
9
0
5
0
9
4
1


## Многомерные массивы

In [48]:
f = lambda x, y: 10 * x + y

In [49]:
b = np.fromfunction(f, (4, 3))
b

array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [50]:
b[3, 1]

31.0

In [51]:
b[1:3, 2]

array([12., 22.])

In [52]:
b[:2, :]

array([[ 0.,  1.,  2.],
       [10., 11., 12.]])

In [53]:
b[:, 0:1]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [54]:
b[:, 0]

array([ 0., 10., 20., 30.])

In [55]:
b[-1]

array([30., 31., 32.])

In [56]:
b[::-1, ::-1]

array([[32., 31., 30.],
       [22., 21., 20.],
       [12., 11., 10.],
       [ 2.,  1.,  0.]])

In [57]:
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              
              [[100, 101, 102],
               [110, 112, 123]]])

In [58]:
c.shape

(2, 2, 3)

In [59]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 123]])

In [60]:
c[..., 2]

array([[  2,  13],
       [102, 123]])

In [61]:
c[..., 0, 2]

array([  2, 102])

In [62]:
for row in b:
    print(row)

[0. 1. 2.]
[10. 11. 12.]
[20. 21. 22.]
[30. 31. 32.]


In [63]:
for elem in b.flat:
    print(elem)

0.0
1.0
2.0
10.0
11.0
12.0
20.0
21.0
22.0
30.0
31.0
32.0


In [64]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [65]:
i = np.array([1, 1, 3, 5, 8])

In [66]:
a[i]

array([ 1,  1,  9, 25, 64], dtype=int32)

In [67]:
j = np.array([[1, 1], [4, 9], [8, 10]])

In [68]:
a[j]

array([[  1,   1],
       [ 16,  81],
       [ 64, 100]], dtype=int32)

# Изменение формы массива

In [69]:
rg = np.random.default_rng(1)
a = np.floor(10*rg.random((3, 4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [70]:
a.shape

(3, 4)

In [71]:
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [72]:
a.reshape(2, 6)

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [73]:
a.reshape((1, 1, a.size))

array([[[5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.]]])

In [74]:
a.T

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [75]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [76]:
a.resize((2, 6))

In [77]:
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [78]:
a.reshape(2, 3, -1)

array([[[5., 9.],
        [1., 9.],
        [3., 4.]],

       [[8., 4.],
        [5., 0.],
        [7., 5.]]])

# Объединение массивов

In [79]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
np.random.seed(19)
b = np.random.randint(1, 10, (2, 5))
b

array([[6, 3, 9, 4, 5],
       [3, 9, 7, 3, 6]])

In [81]:
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [6, 3, 9, 4, 5],
       [3, 9, 7, 3, 6]])

In [82]:
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 6, 3, 9, 4, 5],
       [5, 6, 7, 8, 9, 3, 9, 7, 3, 6]])

In [83]:
np.column_stack((a, b))

array([[0, 1, 2, 3, 4, 6, 3, 9, 4, 5],
       [5, 6, 7, 8, 9, 3, 9, 7, 3, 6]])

In [84]:
np.row_stack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [6, 3, 9, 4, 5],
       [3, 9, 7, 3, 6]])

In [85]:
a = np.array([1, 2, 4, 5])

In [86]:
c = a[:, np.newaxis]

In [87]:
c

array([[1],
       [2],
       [4],
       [5]])

In [88]:
c[3]

array([5])

# Разбиение массива

In [89]:
a = np.floor(10 * rg.random((10, 12)))
a

array([[3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.],
       [9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.],
       [0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.],
       [1., 8., 6., 7., 1., 8., 1., 0., 8., 8., 8., 4.],
       [2., 0., 6., 7., 8., 2., 2., 6., 8., 9., 1., 4.],
       [8., 4., 5., 0., 6., 9., 8., 8., 6., 2., 7., 2.],
       [8., 0., 8., 1., 3., 3., 6., 1., 3., 0., 2., 4.],
       [1., 6., 3., 7., 6., 4., 8., 6., 8., 3., 5., 1.],
       [9., 2., 2., 0., 2., 7., 6., 1., 3., 4., 6., 4.],
       [5., 8., 7., 3., 4., 3., 1., 2., 2., 3., 3., 5.]])

In [90]:
b = np.hsplit(a, 4)
b

[array([[3., 7., 3.],
        [9., 7., 5.],
        [0., 5., 4.],
        [1., 8., 6.],
        [2., 0., 6.],
        [8., 4., 5.],
        [8., 0., 8.],
        [1., 6., 3.],
        [9., 2., 2.],
        [5., 8., 7.]]),
 array([[4., 1., 4.],
        [2., 1., 9.],
        [0., 6., 8.],
        [7., 1., 8.],
        [7., 8., 2.],
        [0., 6., 9.],
        [1., 3., 3.],
        [7., 6., 4.],
        [0., 2., 7.],
        [3., 4., 3.]]),
 array([[2., 2., 7.],
        [5., 1., 6.],
        [5., 2., 8.],
        [1., 0., 8.],
        [2., 6., 8.],
        [8., 8., 6.],
        [6., 1., 3.],
        [8., 6., 8.],
        [6., 1., 3.],
        [1., 2., 2.]]),
 array([[2., 4., 9.],
        [7., 6., 9.],
        [5., 5., 7.],
        [8., 8., 4.],
        [9., 1., 4.],
        [2., 7., 2.],
        [0., 2., 4.],
        [3., 5., 1.],
        [4., 6., 4.],
        [3., 3., 5.]])]

In [91]:
b = np.vsplit(a, 5)
b

[array([[3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.],
        [9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.],
        [1., 8., 6., 7., 1., 8., 1., 0., 8., 8., 8., 4.]]),
 array([[2., 0., 6., 7., 8., 2., 2., 6., 8., 9., 1., 4.],
        [8., 4., 5., 0., 6., 9., 8., 8., 6., 2., 7., 2.]]),
 array([[8., 0., 8., 1., 3., 3., 6., 1., 3., 0., 2., 4.],
        [1., 6., 3., 7., 6., 4., 8., 6., 8., 3., 5., 1.]]),
 array([[9., 2., 2., 0., 2., 7., 6., 1., 3., 4., 6., 4.],
        [5., 8., 7., 3., 4., 3., 1., 2., 2., 3., 3., 5.]])]

In [92]:
b[-1]

array([[9., 2., 2., 0., 2., 7., 6., 1., 3., 4., 6., 4.],
       [5., 8., 7., 3., 4., 3., 1., 2., 2., 3., 3., 5.]])

In [93]:
a = np.arange(10)

In [94]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
b = a.view()

In [96]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a.resize((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [98]:
a[0, 0] = 100

In [99]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [100]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [101]:
b = a.copy()

In [102]:
a[0, 0] = 1000
a

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [103]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

# Линейная алгебра

## Умножение матриц (лин преобразования)

In [104]:
A = np.array([[1, 3, 1],
              [2, 1, 2]])

B = np.array([[4, 1], 
              [2, 2],
              [8, 11]])

In [105]:
A @ B

array([[18, 18],
       [26, 26]])

In [106]:
B @ A

array([[ 6, 13,  6],
       [ 6,  8,  6],
       [30, 35, 30]])

In [107]:
np.dot(A, B)

array([[18, 18],
       [26, 26]])

In [108]:
B.dot(A)

array([[ 6, 13,  6],
       [ 6,  8,  6],
       [30, 35, 30]])

## Матрица на вектор

In [109]:
A = np.array([[1, 0],
              [2, 5]])

v = np.array([1, 3])

A @ v

array([ 1, 17])

In [110]:
A @ v.T

array([ 1, 17])

In [111]:
v @ A

array([ 7, 15])

In [112]:
v.T @ A

array([ 7, 15])

## Транспонирование матриц

In [113]:
A = np.array([[1, 2],
              [3, 4]])

In [114]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [115]:
A.T

array([[1, 3],
       [2, 4]])

## Определитель матрицы

In [116]:
A = np.array([[1, 2, 1],
              [1, 1, 4],
              [2, 3, 6]], dtype=np.float32)

In [117]:
np.linalg.det(A)

-1.0

## Ранг матрицы

In [118]:
A = np.array([[1, 1, 2],
              [2, 1, 2],
              [3, 1, 2]])

In [119]:
np.linalg.matrix_rank(A)

2

## СЛАУ

In [120]:
A = np.array([[3, 1],
              [1, 2]])

b = np.array([9, 8])

In [121]:
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [122]:
A.dot(x)

array([9., 8.])

In [123]:
A = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])

In [124]:
# np.linalg.solve(A, b)

In [125]:
x, res, r, s = np.linalg.lstsq(A, b, rcond=None)
x, res, r, s

(array([ 1.  , -0.95]), array([0.05]), 2, array([4.10003045, 1.09075677]))

## Обратная матрица

In [126]:
A = np.array([[1, 2, 1],
              [1, 1, 4],
              [2, 3, 6]], dtype=np.float32)

B = np.linalg.inv(A)

In [127]:
B

array([[ 6.,  9., -7.],
       [-2., -4.,  3.],
       [-1., -1.,  1.]], dtype=float32)

In [128]:
A.dot(B)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [129]:
B.dot(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

## Собственные вектора и значения

In [130]:
A = np.array([[-1, -6],
              [2, 6]])

num, v = np.linalg.eig(A)

In [131]:
num

array([2., 3.])

In [132]:
v

array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]])